version: '3.8'

services:
  auth_service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./config.yaml:/app/config.yaml
    depends_on:
      - db
    restart: on-failure

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DB_EXTERNAL_PORT=${DB_EXTERNAL_PORT}
      - DB_PORT=${DB_PORT}
    ports:
      - "${DB_EXTERNAL_PORT}:${DB_PORT}" 
    volumes:
      - ./pgdata:/var/lib/postgresql/data
volumes:
  pgdata: